# Generated by Django 6.0.6 on 2026-06-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printpal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filament',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
