# Generated by Django 6.0.6 on 2026-06-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printpal_app', '0002_alter_filament_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='user',
        ),
    ]
