# Generated by Django 6.0.6 on 2026-06-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printpal_app', '0004_brand_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='filament',
            name='weight',
            field=models.CharField(choices=[('0.75', '0.75 kg'), ('0.85', '0.85 kg'), ('3.0', '3.0 kg')], default='0.85'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='status',
            field=models.CharField(choices=[('In work', 'In Work'), ('Repair', 'Repair'), ('Out of order', 'Out Of Order')], default='In work', max_length=50),
        ),
    ]
